name = "cannon-sample-router"
description = "Cannon Router step example usage"
version = "0.0.0"

[contract.Counter]
artifact = "Counter"

[contract.Greeter]
artifact = "Greeter"

[router.Router]
contracts = [
  "Counter",
  "Greeter"
]
depends = [
  "contract.Counter",
  "contract.Greeter"
]

[invoke.setNumber]
target = ["Router"]
func = "setNumber"
args = [3]
depends = ["router.Router"]

[invoke.setGreeting]
target = ["Router"]
func = "setNumber"
args = ["hello world!"]
depends = ["router.Router"]
